### ISSUE TITLE
"flowCore_biexponential_transform" not available for .Call() for package "flowCore"

### ISSUE THREAD

**Issue by pablasimarjot** [RGLab/flowTrans#1]
I am getting this error when I try to use flowTrans to apply biexp optimization.

transformed<-flowTrans(dat=fs[[1]],fun="mclMultivBiexp",dims=c(colnames(fs)1:2]),n2f=FALSE,parameters.only=FALSE)

I updated the library with latest "trunk" (last updated in 2016) and still get the same issue.

**Comment by gfinak** [comment]
Just looking at the trunk branch of `flowCore`:
https://github.com/RGLab/flowCore/blob/f799f8742ba6cc7491072bafbde5b7324f26579b/src/RcppExports.cpp#L11
I see that the function hasn't changed names and is still exported.. 
Can you provide a `reprex` to reproduce your error? (see here https://reprex.tidyverse.org/articles/articles/learn-reprex.html)

**Comment by pablasimarjot** [comment]
Here is a reprex that gives me the same error:

#Include Libraries
library(ggplot2)
library(flowCore)
library(flowStats)
library(flowWorkspace)
library(flowClust)
library(ggcyto)
library(ggridges)
library(gridExtra)
library(CytoML)
library(openCyto)
library(flowViz)
library(devtools)
library(ggpubr)
library(ggjoy)
library(FlowSOM)
library(Rtsne)
library(flowTrans)

#Read in flowset object
data(GvHD)

#Use flowTrans to apply biexponential tranformation optimization on first flowframe of the flowset object 
transformed<-flowTrans(dat=GvHD[[1]],fun="mclMultivBiexp",dims=colnames(GvHD)[1:2],n2f=FALSE,parameters.only=TRUE)

**Comment by gfinak** [comment]
Looks like the name of the function exported by Rcpp has changed and it prefixes a "_"
I've made the change here, if you pull the master branch you'll get the immediate fix. 
It will appear in the BioConductor dev version in the next couple of days.

**Comment by pablasimarjot** [comment]
Thanks. I suspected the underscore with the traceback. Worked like a charm. Thank you.
